export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_WITH_USER = "FETCH_PRODUCTS_WITH_USER";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const SET_PRODUCT = "SET_PRODUCTS";
export const SORT_PRODUCTS = {
  NEW_RELEASE: "NEW_RELEASE",
  RELEASE_DATE: "RELEASE_DATE",
  ALPHABETICAL: "ALPHABETICAL",
  LOW_TO_HIGH: "LOW_TO_HIGH",
  HIGH_TO_LOW: "HIGH_TO_LOW",
};
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const GROUP_TAG = "GROUP_TAG";
